// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  (function() {
    return "use strict";
  });

  this.Panel = (function() {
    function Panel(x, y, width, height) {
      this.type = "PANEL";
      this.x = x;
      this.y = y;
      this.width = width;
      this.height = height;
      this.color = "#000000";
      this.parentComponent = null;
      this.components = [];
      this.zIndex = 0;
    }

    Panel.prototype.draw = function(ctx, windowX, windowY) {
      var i, len, obj, results, sorted;
      this.preprocess(ctx, windowX, windowY);
      this.drawPanel(ctx, windowX, windowY);
      this.postprocess(ctx, windowX, windowY);
      sorted = this.components.sort(function(obj1, obj2) {
        return obj1.zIndex - obj2.zIndex;
      });
      results = [];
      for (i = 0, len = sorted.length; i < len; i++) {
        obj = sorted[i];
        results.push(obj.draw(ctx, windowX + obj.x, windowY + obj.y));
      }
      return results;
    };

    Panel.prototype.drawPanel = function(ctx, windowX, windowY) {
      ctx.fillStyle = this.color;
      return ctx.fillRect(windowX, windowY, this.width, this.height);
    };

    Panel.prototype.preprocess = function(ctx, windowX, windowY) {};

    Panel.prototype.postprocess = function(ctx, windowX, windowY) {};

    Panel.prototype.containsPoint = function(point) {
      return (this.x <= point.clientX && point.clientX <= this.x + this.width) && (this.y <= point.clientY && point.clientY <= this.y + this.height);
    };

    Panel.prototype.runOnTopComponent = function(mouseEvent, eventHandler) {
      return this.components.filter(function(panel) {
        return panel.containsPoint(mouseEvent);
      }).sort(function(panel1, panel2) {
        return -1 * (panel1.zIndex - panel2.zIndex);
      }).slice(0, 1).forEach(eventHandler);
    };

    Panel.prototype.clickHandler = function(event) {
      return this.runOnTopComponent(event, function(component) {
        return component.clickHandler(component.translateEvent(event));
      });
    };

    Panel.prototype.mousedownHandler = function(event) {
      return this.runOnTopComponent(event, function(component) {
        return component.mousedownHandler(component.translateEvent(event));
      });
    };

    Panel.prototype.mouseupHandler = function(event) {
      return this.runOnTopComponent(event, function(component) {
        return component.mouseupHandler(component.translateEvent(event));
      });
    };

    Panel.prototype.mousemoveHandler = function(event) {
      return this.runOnTopComponent(event, function(component) {
        return component.mousemoveHandler(component.translateEvent(event));
      });
    };

    Panel.prototype.mousewheelHandler = function(event) {
      return this.runOnTopComponent(event, function(component) {
        return component.mousewheelHandler(component.translateEvent(event));
      });
    };

    Panel.prototype.touchstartHandler = function(event) {
      return this.runOnTopComponent(event, function(component) {
        return component.touchstartHandler(component.translateEvent(event));
      });
    };

    Panel.prototype.touchmoveHandler = function(event) {
      return this.runOnTopComponent(event, function(component) {
        return component.touchmoveHandler(component.translateEvent(event));
      });
    };

    Panel.prototype.touchendHandler = function(event) {
      return this.runOnTopComponent(event, function(component) {
        return component.touchendHandler(component.translateEvent(event));
      });
    };

    Panel.prototype.translateEvent = function(event) {
      var i, key, len, newEvent, val;
      newEvent = {};
      for (val = i = 0, len = event.length; i < len; val = ++i) {
        key = event[val];
        newEvent[key] = val;
      }
      newEvent.clientX = event.clientX - this.x;
      newEvent.clientY = event.clientY - this.y;
      return newEvent;
    };

    Panel.prototype.keydownHandler = function(key) {
      var i, len, panel, ref, results;
      ref = this.components;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        panel = ref[i];
        results.push(panel.keydownHandler(key));
      }
      return results;
    };

    Panel.prototype.addComponent = function(component) {
      this.components.push(component);
      return this.components.parentComponent = this;
    };

    Panel.prototype.setWindow = function(x, y, width, height) {
      this.x = x;
      this.y = y;
      this.width = width;
      return this.height = height;
    };

    return Panel;

  })();

  this.CanvasPanel = (function(superClass) {
    extend(CanvasPanel, superClass);

    function CanvasPanel(canvas) {
      var copyEvent, instance;
      this.canvas = canvas;
      this.canvas.width = window.innerWidth;
      this.canvas.height = window.innerHeight;
      CanvasPanel.__super__.constructor.call(this, 0, 0, this.canvas.width, this.canvas.height);
      this.canvas.onmousedown = function() {
        return false;
      };
      this.ctx = this.canvas.getContext("2d");
      copyEvent = function() {
        var key, newEvent, val;
        newEvent = {};
        for (key in event) {
          val = event[key];
          newEvent[key] = val;
        }
        return newEvent;
      };
      instance = this;
      this.canvas.addEventListener('click', (function(event) {
        return instance.clickHandler(event);
      }), false);
      this.canvas.addEventListener('mousedown', (function(event) {
        return instance.mousedownHandler(event);
      }), false);
      this.canvas.addEventListener('mouseup', (function(event) {
        return instance.mouseupHandler(event);
      }), false);
      this.canvas.addEventListener('mousemove', (function(event) {
        return instance.mousemoveHandler(event);
      }), false);
      this.canvas.addEventListener('mousewheel', (function(event) {
        return instance.mousewheelHandler(event);
      }), false);
      this.canvas.addEventListener("DOMMouseScroll", (function(event) {
        return instance.mousewheelHandler({
          clientX: event.clientX,
          clientY: event.clientY,
          wheelDelta: event.detail * -1
        });
      }), false);
      this.canvas.addEventListener('touchstart', function(event) {
        var i, len, ref, results, touchEvent;
        event.preventDefault();
        ref = event.changedTouches;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          touchEvent = ref[i];
          results.push(instance.mousedownHandler(touchEvent));
        }
        return results;
      });
      this.canvas.addEventListener('touchmove', function(event) {
        var i, len, ref, results, touchEvent;
        event.preventDefault();
        ref = event.changedTouches;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          touchEvent = ref[i];
          results.push(instance.mousemoveHandler(touchEvent));
        }
        return results;
      });
      this.canvas.addEventListener('touchend', function(event) {
        var i, len, ref, results, touchEvent;
        event.preventDefault();
        ref = event.changedTouches;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          touchEvent = ref[i];
          results.push(instance.clickHandler(touchEvent));
        }
        return results;
      });
    }

    CanvasPanel.prototype.draw = function() {
      this.setWindow(0, 0, window.innerWidth, window.innerHeight);
      this.canvas.width = window.innerWidth;
      this.canvas.height = window.innerHeight;
      return Panel.prototype.draw.call(this, this.ctx, 0, 0);
    };

    return CanvasPanel;

  })(this.Panel);

}).call(this);
